Use conan systemm requirements to install open gl dependencies on ubuntu
Twon/Morpheus pull request #297
Opened 2024-04-28 11:11 UTC by Twon

2024-04-28 16:08 UTC, mintel1 requested changes
I've only tested the change to the conanfile.py locally after doing a quick reinstall of linux. It does the trick, assuming I also make a change to my .conf file, as per my comment below. 
Wondering if the conan conf should be changed via python behind the scenes?

2024-04-28 16:08 UTC, mintel1 commented on conanfile.py
I reinstalled ubuntu on my machine so I could start from scratch.
Once I'd cloned Morpheus, I then edited conanfile.py as per this PR. Here is my output:

```
dpkg-query: no packages found matching libgl-dev
dpkg-query: no packages found matching libgl1-mesa-dev
opengl/system: WARN: System requirements: 'libgl-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
opengl/system: WARN: System requirements: 'libgl1-mesa-dev' are missing but can't install because tools.system.package_manager:mode is 'check'.Please update packages manually or set 'tools.system.package_manager:mode' to 'install' in the [conf] section of the profile, or in the command line using '-c tools.system.package_manager:mode=install'
ERROR: opengl/system: Error in system_requirements() method, line 33
	apt.install_substitutes(["libgl-dev"], ["libgl1-mesa-dev"], update=True, check=True)
	ConanException: None of the installs for the package substitutes succeeded.
```

I needed these lines set.
```
$ cat ~/.conan2/global.conf 
tools.system.package_manager:mode = install
tools.system.package_manager:sudo = True
```

2024-04-28 19:03 UTC, Twon commented
> I've only tested the change to the conanfile.py locally after doing a quick reinstall of linux. It does the trick, assuming I also make a change to my .conf file, as per my comment below. Wondering if the conan conf should be changed via python behind the scenes?

No, I don't believe it should as that would result in Morpheus installing dependencies on a users machine without them necessarily wanting that.  I think a more sensible option would be to provide a useful error message when the dependency is missing and provide the user with the steps to follow if they do wish to follow it.  Also if it does fail to install OpenGL, then Vulkan could still be available on Linux so it should continue successfully as long as at least one under lying render system is available.  Any failure to provide one when there is another viable option should just be a warning the user can choose to address.

2024-04-29 18:55 UTC, Twon commented
I think what probably makes sense is to encourage users to set the check mode in their config as follows:
```
tools.system.package_manager:mode = check
```

Then failures are reported when packages are missing.  Then users can upgrade it to install if they want to install the packages:
https://docs.conan.io/2/reference/tools/system/package_manager.html#configuration-properties-that-affect-how-system-package-managers-are-invoked

Does that sound reasonable?

2024-04-29 20:59 UTC, jmcmon commented
Yes I think that’s a good idea - any other gaps to be filled could be
addressed via a FAQ for example. I agree  that there’s a limit to the
amount of auto-downloading that should be done on a users system

On Mon, 29 Apr 2024 at 19:56, Antony Peacock ***@***.***>
wrote:

> I think what probably makes sense is to encourage users to set the check
> mode in their config as follows:
>
> tools.system.package_manager:mode = check
>
> Then failures are reported when packages are missing. Then users can
> upgrade it to install if they want to install the packages:
>
> https://docs.conan.io/2/reference/tools/system/package_manager.html#configuration-properties-that-affect-how-system-package-managers-are-invoked
>
> Does that sound reasonable?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Twon/Morpheus/pull/297#issuecomment-2083441187>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABP3PQC7VY4HDPJYMF2SZULY72JU5AVCNFSM6AAAAABG44ZHU2VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAOBTGQ2DCMJYG4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2024-04-29 21:06 UTC, mintel1 commented
Yes I think that’s a good idea - any other gaps to be filled could be addressed via a FAQ for example. I agree  that there’s a limit to the amount of auto-downloading that should be done on a users system

2024-05-01 19:55 UTC, mintel1 approved these changes
Looks good to me!

2024-05-06 17:27 UTC, merged